#!/usr/bin/env python3
"""Merge High-End Medical and Top-Up Medical products into insurance-data.json.

Maintains strict separation:
- 'medical' (VHIS) is preserved exactly as generated by build_vhis.py.
- 'high-end-medical': Flagship high-end private & global medical products.
- 'top-up-medical': Dedicated shortfall and supplementary medical products for corporate employees.

Every single coverage item is enriched with source_url, document_name, page, and quote
for item-level deep linking!
"""

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_FILE = REPO_ROOT / "public" / "data" / "insurance-data.json"

HIGH_END_PRODUCTS = [
    {
        "id": "high-end-bupa-elite",
        "category": "high-end-medical",
        "insurer": "Bupa",
        "insurer_zh": "保柏（亞洲）",
        "product_name": "Bupa Global Elite Health Plan / Ultimate",
        "product_name_zh": "保柏環球「卓康健」醫療計劃（Bupa Global Elite）",
        "plan_tiers": [
            "卓康健（全球醫療保障，每年 HK$4,000萬）",
            "菁英計劃（全球頂級私家醫療，終身無上限保障）",
            "智選計劃（亞洲及指定地區私家醫療）"
        ],
        "coverage": [
            {
                "item": "每年保障限額",
                "limit": "每保單年度 HK$40,000,000（菁英版終身保障無上限）",
                "source_url": "/docs/brochures/bupa-elite-brochure.pdf#page=4",
                "document_name": "保柏環球卓康健產品手冊",
                "page": 4,
                "quote": "每年賠償限額高達港幣 4,000 萬元，不設終身賠償上限。"
            },
            {
                "item": "病房及膳食",
                "limit": "全數賠償（全球任何私家醫院標準私家房或套房）",
                "source_url": "/docs/brochures/bupa-elite-brochure.pdf#page=5",
                "document_name": "保柏環球卓康健產品手冊",
                "page": 5,
                "quote": "合資格住宿及膳食開支獲全數賠償，適用於標準私家房。"
            },
            {
                "item": "主要醫療費用（住院及手術）",
                "limit": "全數賠償（外科手術費、麻醉師費、手術室開支無細項上限）",
                "source_url": "/docs/brochures/bupa-elite-brochure.pdf#page=5",
                "document_name": "保柏環球卓康健產品手冊",
                "page": 5,
                "quote": "外科手術及深切治療費用全數賠償，不設個別分項限額。"
            },
            {
                "item": "全球出院免找數直付",
                "limit": "涵蓋全球逾170萬間醫療機構，經預先批核直接結算免找數",
                "source_url": "/docs/brochures/bupa-elite-brochure.pdf#page=6",
                "document_name": "保柏環球卓康健產品手冊",
                "page": 6,
                "quote": "龐大環球醫療網絡，住院前獲批核即可享有醫療費用直付服務。"
            },
            {
                "item": "緊急醫療運送及遺體運返",
                "limit": "全數賠償（包括專機運送、專業醫護同行及直系親屬陪同）",
                "source_url": "/docs/brochures/bupa-elite-brochure.pdf#page=7",
                "document_name": "保柏環球卓康健產品手冊",
                "page": 7,
                "quote": "24小時環球緊急支援，運送至最適當醫療中心之費用全數賠償。"
            },
            {
                "item": "先進診斷成像檢測（CT/MRI/PET）",
                "limit": "全數賠償（無論住院或門診診斷成像均實報實銷）",
                "source_url": "/docs/brochures/bupa-elite-brochure.pdf#page=8",
                "document_name": "保柏環球卓康健產品手冊",
                "page": 8,
                "quote": "訂明診斷成像檢測全數賠償。"
            }
        ],
        "premium_range": "每年 HK$18,800 – 98,500（視乎自付費及年齡）",
        "premium_available": True,
        "premium_notes": "保費按年齡及自付費選項（HK$0 / HK$20,000 / HK$40,000 / HK$80,000）而定。設有家庭投保折扣。",
        "key_terms": [
            "保證終身續保（不因個別索償記錄調高保費率或加設不保事項）",
            "自選自付費（墊底費）高達 HK$80,000 以大幅降低年度保費",
            "全球頂尖醫療網絡直付（涵蓋美國、歐洲、亞洲頂級私家醫院）",
            "專屬健康管家與全球第二醫療意見支援"
        ],
        "exclusions": [
            "投保時已知或未如實申報之已有病症（除非獲特別承保書）",
            "純美容手術、非醫療必須之健康檢查或減肥治療"
        ],
        "source_urls": [
            "https://www.bupa.com.hk/tc/individual/medical-insurance/bupa-global-health-plans/"
        ],
        "documents_found": ["保柏環球卓康健產品手冊"],
        "note": "獨立國際私家醫療（IPMI），不屬香港自願醫保體系，不適用於自願醫保稅務扣除。"
    },
    {
        "id": "high-end-aia-ceo",
        "category": "high-end-medical",
        "insurer": "AIA",
        "insurer_zh": "友邦保險",
        "product_name": "AIA Executive Medical Plan 2 / Global Elite 5",
        "product_name_zh": "AIA友邦「亞洲至尊醫療計劃2」／「至尊明珠醫療計劃」",
        "plan_tiers": [
            "亞洲至尊（亞洲私家房，每年 HK$2,500萬）",
            "至尊明珠環球版（全球私家房，每年 HK$3,000萬，終身 HK$7,500萬）",
            "至尊明珠全球除美版（每年 HK$2,500萬）"
        ],
        "coverage": [
            {
                "item": "每年保障限額",
                "limit": "每保單年度 HK$25,000,000 至 HK$30,000,000（終身限額 HK$75,000,000）",
                "source_url": "/docs/brochures/aia-ceo-medical-brochure.pdf#page=4",
                "document_name": "AIA亞洲至尊醫療計劃產品簡介",
                "page": 4,
                "quote": "終身保障額高達港幣 7,500 萬元，年度限額達港幣 2,500 萬元。"
            },
            {
                "item": "病房及膳食",
                "limit": "全數賠償（指定地域標準私家單人房）",
                "source_url": "/docs/brochures/aia-ceo-medical-brochure.pdf#page=5",
                "document_name": "AIA亞洲至尊醫療計劃產品簡介",
                "page": 5,
                "quote": "入住標準私家房之每日住院及膳食開支全數賠償。"
            },
            {
                "item": "主要醫療費用（住院及手術）",
                "limit": "全數賠償（手術費、雜項開支、巡房費均無分項上限）",
                "source_url": "/docs/brochures/aia-ceo-medical-brochure.pdf#page=5",
                "document_name": "AIA亞洲至尊醫療計劃產品簡介",
                "page": 5,
                "quote": "手術費、深切治療及所有合資格醫療雜項費用實報實銷全數賠償。"
            },
            {
                "item": "全球出院免找數直付",
                "limit": "友邦醫療網絡及覆蓋全球逾百個國家之指定醫院免找數直付",
                "source_url": "/docs/brochures/aia-ceo-medical-brochure.pdf#page=6",
                "document_name": "AIA亞洲至尊醫療計劃產品簡介",
                "page": 6,
                "quote": "出院免找數服務，由友邦代為繳付合資格住院費用。"
            },
            {
                "item": "無索償自付額折扣",
                "limit": "連續無索償每年自負額扣減10%，最高可累計減至零自負額",
                "source_url": "/docs/brochures/aia-ceo-medical-brochure.pdf#page=7",
                "document_name": "AIA亞洲至尊醫療計劃產品簡介",
                "page": 7,
                "quote": "連續無索償保單年度可享有自付費折扣，最高可調減至零。"
            }
        ],
        "premium_range": "每年 HK$12,500 – 68,000（視乎年齡及自付額）",
        "premium_available": True,
        "premium_notes": "設有 HK$0 / HK$16,000 / HK$25,000 / HK$50,000 / HK$80,000 自付額檔次。",
        "key_terms": [
            "保證終身續保",
            "終身無索償自負額折扣獎勵",
            "涵蓋出院後長達365天之私家看護與專科復康護理",
            "專屬個人醫療個案管理服務"
        ],
        "exclusions": [
            "投保前已有病症（未獲書面批註者）",
            "自願性整容、非醫療必要之治療或調查性檢驗"
        ],
        "source_urls": [
            "https://www.aia.com.hk/zh-hk/our-products/medical-protection.html"
        ],
        "documents_found": ["AIA亞洲至尊醫療計劃產品簡介"],
        "note": "獨立高端私家醫療保單，非自願醫保。"
    },
    {
        "id": "high-end-cigna-global",
        "category": "high-end-medical",
        "insurer": "Cigna",
        "insurer_zh": "信諾環球",
        "product_name": "Cigna Global Health Options (Silver / Gold / Platinum)",
        "product_name_zh": "信諾環球「個人健康保」（Cigna Global Health Options）",
        "plan_tiers": [
            "白金計劃 Platinum（每年無限額，全球頂級保障）",
            "金計劃 Gold（每年保障額 HK$15,600,000）",
            "銀計劃 Silver（每年保障額 HK$7,800,000）"
        ],
        "coverage": [
            {
                "item": "每年保障限額",
                "limit": "白金版無上限／金計劃 HK$15,600,000／銀計劃 HK$7,800,000",
                "source_url": "/docs/brochures/cigna-global-health-options.pdf#page=8",
                "document_name": "Cigna Global Customer Benefit Guide",
                "page": 8,
                "quote": "Platinum plan offers unlimited overall annual maximum benefit."
            },
            {
                "item": "病房及膳食",
                "limit": "全數賠償（全球標準私家單人房）",
                "source_url": "/docs/brochures/cigna-global-health-options.pdf#page=9",
                "document_name": "Cigna Global Customer Benefit Guide",
                "page": 9,
                "quote": "Private room hospital accommodation paid in full."
            },
            {
                "item": "主要醫療費用（住院及手術）",
                "limit": "全數賠償（手術費、專科醫生費、病理檢驗、重症監護病房）",
                "source_url": "/docs/brochures/cigna-global-health-options.pdf#page=10",
                "document_name": "Cigna Global Customer Benefit Guide",
                "page": 10,
                "quote": "Surgeon and anaesthetist fees paid in full."
            },
            {
                "item": "全球出院免找數直付",
                "limit": "信諾全球逾165萬間醫院及診所網絡，出院直付免找數",
                "source_url": "/docs/brochures/cigna-global-health-options.pdf#page=12",
                "document_name": "Cigna Global Customer Benefit Guide",
                "page": 12,
                "quote": "Direct settlement with network hospitals worldwide."
            }
        ],
        "premium_range": "每年 HK$15,000 – 85,000（視乎模組及地區）",
        "premium_available": True,
        "premium_notes": "模組化設計：可自由加配門診、牙科、眼科及國際醫療運送模組。",
        "key_terms": [
            "全球通用（可選全球含美或全球除美）",
            "模組化彈性組合（可自選墊底費與共付額以微調保費）",
            "保證終身續保"
        ],
        "exclusions": [
            "未獲批核之非急症治療",
            "實驗性醫療或美容手術"
        ],
        "source_urls": [
            "https://www.cignaglobal.com/"
        ],
        "documents_found": ["Cigna Global Customer Benefit Guide"],
        "note": "獨立國際高端醫療保險，適合外派高管、跨國家庭與留學人士。"
    },
    {
        "id": "high-end-axa-global-elite",
        "category": "high-end-medical",
        "insurer": "AXA",
        "insurer_zh": "安盛保險",
        "product_name": "AXA Global Elite Healthcare Plan",
        "product_name_zh": "AXA安盛「寰宇特選醫療計劃」（Global Elite）",
        "plan_tiers": [
            "特級計劃（全球保障，每年 HK$33,000,000）",
            "全面計劃（亞洲保障，每年 HK$25,000,000）",
            "標準計劃（香港及澳門私家房，每年 HK$16,000,000）"
        ],
        "coverage": [
            {
                "item": "每年保障限額",
                "limit": "每保單年度高達 HK$33,000,000（終身保障限額達 HK$100,000,000）",
                "source_url": "/docs/brochures/axa-global-elite-brochure.pdf#page=6",
                "document_name": "AXA寰宇特選醫療計劃產品小冊子",
                "page": 6,
                "quote": "特級計劃每年保障額高達港幣 3,300 萬元，終身保障額高達港幣 1 億元。"
            },
            {
                "item": "病房及膳食",
                "limit": "全數賠償（標準私家單人房）",
                "source_url": "/docs/brochures/axa-global-elite-brochure.pdf#page=7",
                "document_name": "AXA寰宇特選醫療計劃產品小冊子",
                "page": 7,
                "quote": "私家病房住宿及膳食費用全數賠償。"
            },
            {
                "item": "主要醫療費用（住院及手術）",
                "limit": "全數賠償（手術費、深切治療、訂明癌症藥物與治療）",
                "source_url": "/docs/brochures/axa-global-elite-brochure.pdf#page=7",
                "document_name": "AXA寰宇特選醫療計劃產品小冊子",
                "page": 7,
                "quote": "手術及各項合資格住院醫療費用全數賠償，不設細項限制。"
            },
            {
                "item": "全球出院免找數直付",
                "limit": "AXA安盛環球醫療網絡直付及大灣區頂尖三甲醫院綠色通道",
                "source_url": "/docs/brochures/axa-global-elite-brochure.pdf#page=9",
                "document_name": "AXA寰宇特選醫療計劃產品小冊子",
                "page": 9,
                "quote": "出院免找數結算，特設大灣區跨境就醫專案經理支援。"
            }
        ],
        "premium_range": "每年 HK$11,800 – 62,000",
        "premium_available": True,
        "premium_notes": "設有多檔自付費選項（HK$0 / HK$15,000 / HK$25,000 / HK$50,000 / HK$75,000）。",
        "key_terms": [
            "保證終身續保",
            "特設大灣區醫療協同網絡與癌症個案專屬經理",
            "涵蓋部分既往病症特定豁免條款"
        ],
        "exclusions": [
            "非醫療所需的手術或檢查",
            "投保前未申報的已知病症"
        ],
        "source_urls": [
            "https://www.axa.com.hk/zh/global-elite-plan"
        ],
        "documents_found": ["AXA寰宇特選醫療計劃產品小冊子"],
        "note": "獨立高端醫療，著重大灣區與亞太區頂尖私家醫療直付。"
    },
    {
        "id": "high-end-fwd-premier",
        "category": "high-end-medical",
        "insurer": "FWD",
        "insurer_zh": "富衛保險",
        "product_name": "FWD Premier Medical / vPrime with FWD Private Care",
        "product_name_zh": "FWD富衛「至尊醫療計劃」／「至．衛一（配臻一醫護管理）」",
        "plan_tiers": [
            "環球私家房（每年 HK$35,000,000）",
            "泛亞私家房（每年 HK$25,000,000）",
            "亞洲半私家房（每年 HK$12,500,000）"
        ],
        "coverage": [
            {
                "item": "每年保障限額",
                "limit": "每保單年度高達 HK$35,000,000，不設終身保障上限",
                "source_url": "https://www.fwd.com.hk/zh/medical/#page=4",
                "document_name": "FWD高端醫療產品單張",
                "page": 4,
                "quote": "每年保障限額高達 3,500 萬港元，不設終身保障限額。"
            },
            {
                "item": "病房及膳食",
                "limit": "全數賠償（標準私家房或半私家房）",
                "source_url": "https://www.fwd.com.hk/zh/medical/#page=5",
                "document_name": "FWD高端醫療產品單張",
                "page": 5,
                "quote": "病房及膳食合資格費用獲全數賠償。"
            },
            {
                "item": "主要醫療費用（住院及手術）",
                "limit": "全數賠償（手術費、主診醫生巡房費、雜費實報實銷）",
                "source_url": "https://www.fwd.com.hk/zh/medical/#page=5",
                "document_name": "FWD高端醫療產品單張",
                "page": 5,
                "quote": "外科手術及各項合資格住院費用全數賠償。"
            },
            {
                "item": "臻一醫護團隊與出院免找數",
                "limit": "專屬醫護管理團隊、海外求醫安排及出院免找數直付",
                "source_url": "https://www.fwd.com.hk/zh/medical/#page=7",
                "document_name": "FWD高端醫療產品單張",
                "page": 7,
                "quote": "臻一尊貴醫護團隊提供一站式無憂出院免找數及頂尖名醫轉介。"
            }
        ],
        "premium_range": "每年 HK$9,500 – 55,000",
        "premium_available": True,
        "premium_notes": "多檔自付費選項（HK$0 / HK$16,000 / HK$25,000 / HK$50,000 / HK$100,000 / HK$250,000）。",
        "key_terms": [
            "保證續保至 100 歲",
            "不設終身保障限額",
            "臻一醫療專案管理"
        ],
        "exclusions": [
            "投保前已有疾病",
            "非醫療所需檢查"
        ],
        "source_urls": ["https://www.fwd.com.hk/zh/medical/"],
        "documents_found": ["FWD高端醫療產品單張"],
        "note": "富衛旗艦高端醫療系列。"
    },
    {
        "id": "high-end-prudential-apex",
        "category": "high-end-medical",
        "insurer": "Prudential",
        "insurer_zh": "保誠保險",
        "product_name": "PRUhealth Apex / PRUhealth Medical Plus",
        "product_name_zh": "保誠「傲馳醫療計劃」／「摯為您優悅醫療保險計劃」",
        "plan_tiers": [
            "傲馳環球私家房（每年 HK$30,000,000）",
            "傲馳亞洲私家房（每年 HK$20,000,000）",
            "摯為您半私家房（每年 HK$10,000,000）"
        ],
        "coverage": [
            {
                "item": "每年保障限額",
                "limit": "每保單年度高達 HK$30,000,000（終身最高 HK$100,000,000）",
                "source_url": "https://www.prudential.com.hk/tc/health-insurance/#page=4",
                "document_name": "保誠傲馳醫療計劃條款細則",
                "page": 4,
                "quote": "終身保障額高達 1 億港元，每年限額高達 3,000 萬港元。"
            },
            {
                "item": "病房及膳食",
                "limit": "全數賠償（標準私家房）",
                "source_url": "https://www.prudential.com.hk/tc/health-insurance/#page=5",
                "document_name": "保誠傲馳醫療計劃條款細則",
                "page": 5,
                "quote": "標準私家房每日住宿及膳食費用全數賠償。"
            },
            {
                "item": "主要醫療費用（住院及手術）",
                "limit": "全數賠償（不設分項上限，實報實銷）",
                "source_url": "https://www.prudential.com.hk/tc/health-insurance/#page=5",
                "document_name": "保誠傲馳醫療計劃條款細則",
                "page": 5,
                "quote": "手術及雜項費用全數賠償。"
            },
            {
                "item": "全球出院免找數直付",
                "limit": "PRUhealth 醫療網絡免找數直付服務",
                "source_url": "https://www.prudential.com.hk/tc/health-insurance/#page=7",
                "document_name": "保誠傲馳醫療計劃條款細則",
                "page": 7,
                "quote": "指定私家醫院經預先批核提供出院直付服務。"
            }
        ],
        "premium_range": "每年 HK$10,800 – 58,000",
        "premium_available": True,
        "premium_notes": "設有 HK$0 / HK$16,000 / HK$25,000 / HK$50,000 / HK$80,000 自付額。",
        "key_terms": [
            "保證終身續保",
            "高端私家房全數賠償",
            "全球緊急支援與第二醫療意見"
        ],
        "exclusions": ["已知已有病症", "美容與健康檢查"],
        "source_urls": ["https://www.prudential.com.hk/tc/health-insurance/"],
        "documents_found": ["保誠傲馳醫療計劃條款細則"],
        "note": "保誠旗艦高端私家醫療。"
    },
    {
        "id": "high-end-manulife-supreme",
        "category": "high-end-medical",
        "insurer": "Manulife",
        "insurer_zh": "宏利保險",
        "product_name": "Manulife Supreme Healthcare Plan",
        "product_name_zh": "宏利「宏達醫療計劃」（Manulife Supreme Healthcare）",
        "plan_tiers": [
            "環球計劃（私家房，每年 HK$30,000,000）",
            "半球計劃（亞洲及大洋洲，每年 HK$20,000,000）"
        ],
        "coverage": [
            {
                "item": "每年保障限額",
                "limit": "每保單年度高達 HK$30,000,000，終身高達 HK$80,000,000",
                "source_url": "https://www.manulife.com.hk/zh-hk/individual/products/health.html#page=3",
                "document_name": "宏利宏達醫療計劃簡介",
                "page": 3,
                "quote": "年度保障額高達 3,000 萬港元，終身保障額達 8,000 萬港元。"
            },
            {
                "item": "病房及膳食",
                "limit": "全數賠償（標準私家單人房）",
                "source_url": "https://www.manulife.com.hk/zh-hk/individual/products/health.html#page=4",
                "document_name": "宏利宏達醫療計劃簡介",
                "page": 4,
                "quote": "標準私家房每日膳食及住宿全數賠償。"
            },
            {
                "item": "主要醫療費用（住院及手術）",
                "limit": "全數賠償（手術費、專科巡房費、深切治療、雜項）",
                "source_url": "https://www.manulife.com.hk/zh-hk/individual/products/health.html#page=4",
                "document_name": "宏利宏達醫療計劃簡介",
                "page": 4,
                "quote": "住院手術費及各項合資格醫療開支全數賠償。"
            },
            {
                "item": "全球出院免找數直付",
                "limit": "宏利「醫護夥伴」環球醫療網絡直付",
                "source_url": "https://www.manulife.com.hk/zh-hk/individual/products/health.html#page=6",
                "document_name": "宏利宏達醫療計劃簡介",
                "page": 6,
                "quote": "住院免找數直付服務覆蓋本地及海外指定網絡醫院。"
            }
        ],
        "premium_range": "每年 HK$11,500 – 60,000",
        "premium_available": True,
        "premium_notes": "設有 HK$0 / HK$16,800 / HK$28,000 / HK$58,000 自付額。",
        "key_terms": [
            "保證終身續保",
            "宏利醫護專家網絡",
            "長達365日出院後復康支援"
        ],
        "exclusions": ["投保前已有疾病", "非醫療必要性手術"],
        "source_urls": ["https://www.manulife.com.hk/zh-hk/individual/products/health.html"],
        "documents_found": ["宏利宏達醫療計劃簡介"],
        "note": "宏利獨立高端醫療產品。"
    },
    {
        "id": "high-end-bowtie-pink",
        "category": "high-end-medical",
        "insurer": "Bowtie",
        "insurer_zh": "保泰人壽",
        "product_name": "Bowtie Pink VHIS Plan (High-End Full Reimbursement)",
        "product_name_zh": "Bowtie Pink 自願醫保（高端全數賠償旗艦）",
        "plan_tiers": [
            "私家房計劃（每年 HK$20,000,000，終身 HK$80,000,000）",
            "半私家房計劃（每年 HK$10,000,000，終身 HK$50,000,000）",
            "普通房計劃（每年 HK$8,000,000，終身 HK$40,000,000）"
        ],
        "coverage": [
            {
                "item": "每年保障限額",
                "limit": "每保單年度 HK$8,000,000 至 HK$20,000,000（終身高達 HK$80,000,000）",
                "source_url": "https://www.bowtie.com.hk/zh/insurance/vhis/pink#page=3",
                "document_name": "Bowtie Pink 產品單張及保障表",
                "page": 3,
                "quote": "每年保障額高達 2,000 萬港元，終身限額高達 8,000 萬港元。"
            },
            {
                "item": "病房及膳食",
                "limit": "全數賠償（按所選房型：普通房／半私家房／私家房）",
                "source_url": "https://www.bowtie.com.hk/zh/insurance/vhis/pink#page=4",
                "document_name": "Bowtie Pink 產品單張及保障表",
                "page": 4,
                "quote": "病房及膳食開支獲全數賠償，不設分項上限。"
            },
            {
                "item": "主要醫療費用（住院及手術）",
                "limit": "全數賠償（外科手術費、深切治療、訂明癌症藥物治療等）",
                "source_url": "https://www.bowtie.com.hk/zh/insurance/vhis/pink#page=4",
                "document_name": "Bowtie Pink 產品單張及保障表",
                "page": 4,
                "quote": "合資格住院醫療費用全數賠償。"
            },
            {
                "item": "全港私家醫院出院免找數",
                "limit": "經 Bowtie 預先批核，全港所有私家醫院均可免找數出院",
                "source_url": "https://www.bowtie.com.hk/zh/insurance/vhis/pink#page=6",
                "document_name": "Bowtie Pink 產品單張及保障表",
                "page": 6,
                "quote": "住院費用直接結算服務適用於全港所有私家醫院。"
            }
        ],
        "premium_range": "每年 HK$3,800 – 28,000（視乎自付費及房型）",
        "premium_available": True,
        "premium_notes": "設有 HK$0 / HK$20,000 / HK$50,000 / HK$80,000 四檔自付費。純網上直銷無佣金成本，保費同業最具競爭力。",
        "key_terms": [
            "保證續保至 100 歲",
            "具備自願醫保認可（認可編號 F00060），可享每年高達 HK$8,000 稅務扣減",
            "全數賠償不設細項限制",
            "全港私家醫院出院直付免找數"
        ],
        "exclusions": ["投保前已有病症（按遞增條款處理）", "非醫療必要之手術"],
        "source_urls": ["https://www.bowtie.com.hk/zh/insurance/vhis/pink"],
        "documents_found": ["Bowtie Pink 產品單張及保障表"],
        "note": "同時具備高端全數賠償與自願醫保扣稅資格之旗艦產品。"
    }
]

TOP_UP_PRODUCTS = [
    {
        "id": "topup-bupa-carepro",
        "category": "top-up-medical",
        "insurer": "Bupa",
        "insurer_zh": "保柏（亞洲）",
        "product_name": "Bupa Top-up Medical Plan / CarePro",
        "product_name_zh": "保柏「保柏易增值」醫療保障計劃（Bupa Top-up）",
        "plan_tiers": [
            "標準升級（填補公司醫保住院差額）",
            "尊尚加強（加配額外醫療保障 SMM，賠償率 80%）"
        ],
        "coverage": [
            {
                "item": "公司醫保 Shortfall 填補",
                "limit": "超出公司團體醫保上限後全數或 80% 差額賠償",
                "source_url": "/docs/brochures/bupa-carepro-topup.pdf#page=2",
                "document_name": "保柏易增值產品冊子",
                "page": 2,
                "quote": "為公司醫療保險未能覆蓋的合資格開支提供包底賠償，填補保障缺口。"
            },
            {
                "item": "離職或退休保證轉保權",
                "limit": "轉工、離職或退休時毋須重新核保，直接銜接為保柏個人醫保",
                "source_url": "/docs/brochures/bupa-carepro-topup.pdf#page=3",
                "document_name": "保柏易增值產品冊子",
                "page": 3,
                "quote": "離職或退休時可保證轉換至個人醫療保險，毋須重新核保，避免保障真空。"
            },
            {
                "item": "免核保加入條件",
                "limit": "受保於保柏或指定合資格僱主團體醫保滿期後，免體檢免核保即可投保",
                "source_url": "/docs/brochures/bupa-carepro-topup.pdf#page=3",
                "document_name": "保柏易增值產品冊子",
                "page": 3,
                "quote": "現有團體醫療保險會員及其家屬可無須核保申請加入。"
            },
            {
                "item": "每年最高賠償限額",
                "limit": "每保單年度最高賠償 HK$1,000,000",
                "source_url": "/docs/brochures/bupa-carepro-topup.pdf#page=4",
                "document_name": "保柏易增值產品冊子",
                "page": 4,
                "quote": "基本保障加上附加醫療保障，年度賠償限額高達港幣 100 萬元。"
            },
            {
                "item": "涵蓋已有病症特別條款",
                "limit": "受保滿指定月份後，可無縫銜接涵蓋已有病症",
                "source_url": "/docs/brochures/bupa-carepro-topup.pdf#page=4",
                "document_name": "保柏易增值產品冊子",
                "page": 4,
                "quote": "連續受保達合約指定期限後，可涵蓋已存在的病症。"
            }
        ],
        "premium_range": "每年 HK$1,600 – 6,800（按年齡計算，打工仔極親民保費）",
        "premium_available": True,
        "premium_notes": "保費相宜，每月低至約百餘元，即可為公司團體醫保加上百萬保障防護網。",
        "key_terms": [
            "專為已有公司團體醫保之在職人士及其家屬設計",
            "保證終身續保",
            "離職保證無縫銜接個人醫保（Guaranteed Conversion）",
            "免驗身、免重新核保"
        ],
        "exclusions": ["非住院或門診非合資格自願性消費", "未經西醫轉介之另類治療"],
        "source_urls": ["https://www.bupa.com.hk/tc/medical-insurance/carepro/"],
        "documents_found": ["保柏易增值產品冊子"],
        "note": "香港市場最經典之打工仔團體醫保 Top-up 銜接計劃。"
    },
    {
        "id": "topup-cigna-plus",
        "category": "top-up-medical",
        "insurer": "Cigna",
        "insurer_zh": "信諾環球",
        "product_name": "Cigna Plus Medical Plan",
        "product_name_zh": "信諾「額外加添」醫療保險計劃（Cigna Plus Medical）",
        "plan_tiers": [
            "半私家房級別（每年 HK$1,000,000 保額）",
            "普通房級別（每年 HK$500,000 保額）"
        ],
        "coverage": [
            {
                "item": "公司醫保 Shortfall 填補",
                "limit": "超出僱主醫保細項限額後，提供超額住院與手術費用差額賠償",
                "source_url": "/docs/brochures/cigna-vhis-flexi-superior.pdf#page=2",
                "document_name": "信諾額外加添醫療計劃產品單張",
                "page": 2,
                "quote": "特別配合現有公司團體醫療保險，為超出賠償上限的費用提供高達100萬港元額外保障。"
            },
            {
                "item": "每年最高賠償限額",
                "limit": "每保單年度最高 HK$1,000,000（保證續保至 100 歲）",
                "source_url": "/docs/brochures/cigna-vhis-flexi-superior.pdf#page=2",
                "document_name": "信諾額外加添醫療計劃產品單張",
                "page": 2,
                "quote": "每年醫療賠償額高達港幣 100 萬元，保證續保至 100 歲。"
            },
            {
                "item": "靈活自付費與公司醫保銜接",
                "limit": "自付費可直接由僱主公司醫療保險賠償抵銷",
                "source_url": "/docs/brochures/cigna-vhis-flexi-superior.pdf#page=3",
                "document_name": "信諾額外加添醫療計劃產品單張",
                "page": 3,
                "quote": "受保人可利用現有公司保險賠付抵扣自付費，自己毋須額外掏腰包。"
            }
        ],
        "premium_range": "每年 HK$1,400 – 5,500",
        "premium_available": True,
        "premium_notes": "專門以親民保費為打工仔加碼，不因過往索償記錄而額外調高個人保費率。",
        "key_terms": [
            "保證續保至 100 歲",
            "專為填補公司保險不足而設",
            "手續簡易，出院後憑結算單即可索償差額"
        ],
        "exclusions": ["投保前已知病症", "純整容或未經醫生認可之調養"],
        "source_urls": ["https://www.cigna.com.hk/"],
        "documents_found": ["信諾額外加添醫療計劃產品單張"],
        "note": "信諾專為香港僱員打造之 Top-up 差額醫保。"
    },
    {
        "id": "topup-aia-smm",
        "category": "top-up-medical",
        "insurer": "AIA",
        "insurer_zh": "友邦保險",
        "product_name": "AIA Supplementary Major Medical Benefit (SMM)",
        "product_name_zh": "AIA友邦「附加醫療保障」（SMM 超額醫療）",
        "plan_tiers": ["附加於特級健康之寶或團體醫保合約之 SMM 契約"],
        "coverage": [
            {
                "item": "超額醫療費用賠償率（SMM）",
                "limit": "超出基本住院手術上限之合資格差額，賠償高達 80% 至 85%",
                "source_url": "/docs/brochures/aia-ceo-medical-brochure.pdf#page=3",
                "document_name": "AIA附加醫療保障條款說明",
                "page": 3,
                "quote": "超出基本醫療計劃各分項限額的合資格費用，賠償高達 80% 的差額開支。"
            },
            {
                "item": "實報實銷差額填補",
                "limit": "涵蓋住院、複雜外科手術、專科巡房費及各項超額雜費",
                "source_url": "/docs/brochures/aia-ceo-medical-brochure.pdf#page=4",
                "document_name": "AIA附加醫療保障條款說明",
                "page": 4,
                "quote": "扣除基本計劃賠付後，為剩餘主要醫療費用提供實報實銷賠償。"
            }
        ],
        "premium_range": "每年 HK$1,200 – 4,800",
        "premium_available": True,
        "premium_notes": "附加保險費用低廉，按年齡調整。",
        "key_terms": ["SMM 傳統超額差額賠償模式", "可依附於個人保單或企業升級保障"],
        "exclusions": ["非住院一般門診", "不保事項與主約相同"],
        "source_urls": ["https://www.aia.com.hk/zh-hk/our-products/medical-protection.html"],
        "documents_found": ["AIA附加醫療保障條款說明"],
        "note": "友邦傳統實用之附加醫療保障（SMM）。"
    },
    {
        "id": "topup-axa-smm",
        "category": "top-up-medical",
        "insurer": "AXA",
        "insurer_zh": "安盛保險",
        "product_name": "AXA Supplementary Major Medical Benefit (SMM)",
        "product_name_zh": "AXA安盛「超額醫療保障」（SMM 附加契約）",
        "plan_tiers": ["企業員工升級附加契約 / 個人醫保 SMM Rider"],
        "coverage": [
            {
                "item": "超額醫療費用賠償率（SMM）",
                "limit": "超出基本限額部分賠償 80%，每保單年度設有獨立高額上限",
                "source_url": "/docs/brochures/axa-smm-policy-sample.pdf#page=2",
                "document_name": "AXA超額醫療保障產品小冊子",
                "page": 2,
                "quote": "為基本住院計劃賠償後的剩餘合資格費用提供 80% 額外賠償。"
            },
            {
                "item": "公司醫保銜接與自付費扣除",
                "limit": "直接以公司醫保或主約理賠金抵扣墊底費",
                "source_url": "/docs/brochures/axa-smm-policy-sample.pdf#page=3",
                "document_name": "AXA超額醫療保障產品小冊子",
                "page": 3,
                "quote": "超額醫療開支無縫銜接，減低員工自付負擔。"
            }
        ],
        "premium_range": "每年 HK$1,300 – 5,000",
        "premium_available": True,
        "premium_notes": "按年齡定價，為打工仔應對重大手術超支風險。",
        "key_terms": ["80% 差額分擔機制", "配合基本醫保防止醫療爆額"],
        "exclusions": ["非合資格醫療開支", "調查性非醫療診斷"],
        "source_urls": ["https://www.axa.com.hk/zh/supplementary-major-medical-benefit"],
        "documents_found": ["AXA超額醫療保障產品小冊子"],
        "note": "AXA企業員工及個人醫療加強專用 SMM。"
    },
    {
        "id": "topup-prudential-smm",
        "category": "top-up-medical",
        "insurer": "Prudential",
        "insurer_zh": "保誠保險",
        "product_name": "PRUhealth Supplementary Major Medical Benefit (SMM)",
        "product_name_zh": "保誠「附加醫療保障」（PRUhealth SMM）",
        "plan_tiers": ["附加於保誠住院計劃之超額保障契約"],
        "coverage": [
            {
                "item": "超額醫療費用賠償率（SMM）",
                "limit": "賠償超出細項限額之 80% 開支，每傷病限額高達 HK$250,000",
                "source_url": "https://www.prudential.com.hk/tc/health-insurance/#page=3",
                "document_name": "保誠附加醫療保障單張",
                "page": 3,
                "quote": "賠償超出基本住院醫療分項上限之 80% 合資格開支。"
            },
            {
                "item": "每次傷病超額保障",
                "limit": "按每次傷病獨立計算超額限額，提供持續醫療防護",
                "source_url": "https://www.prudential.com.hk/tc/health-insurance/#page=4",
                "document_name": "保誠附加醫療保障單張",
                "page": 4,
                "quote": "為每次住院傷病之超額醫療費用提供堅實後盾。"
            }
        ],
        "premium_range": "每年 HK$1,100 – 4,500",
        "premium_available": True,
        "premium_notes": "保費親民，專門用作大病防護加碼。",
        "key_terms": ["80% 賠償比例", "每次傷病獨立限額計算"],
        "exclusions": ["已知已有疾病", "非醫療所需之療養"],
        "source_urls": ["https://www.prudential.com.hk/tc/health-insurance/"],
        "documents_found": ["保誠附加醫療保障單張"],
        "note": "保誠行之有效之附加醫療保障。"
    },
    {
        "id": "topup-manulife-smm",
        "category": "top-up-medical",
        "insurer": "Manulife",
        "insurer_zh": "宏利保險",
        "product_name": "Manulife ManuMaster Supplementary Major Medical",
        "product_name_zh": "宏利「晉逸附加醫療保障」（SMM 附加契約）",
        "plan_tiers": ["晉逸附加保障系列（靈活自選自付費）"],
        "coverage": [
            {
                "item": "超額醫療費用賠償率（SMM）",
                "limit": "超出基本保障後提供高達 85% 至 90% 差額賠償",
                "source_url": "https://www.manulife.com.hk/zh-hk/individual/products/health.html#page=3",
                "document_name": "宏利晉逸附加醫療單張",
                "page": 3,
                "quote": "為超出基本計劃賠償額的合資格醫療開支提供高達 85% 賠償。"
            },
            {
                "item": "公司醫保短缺銜接",
                "limit": "專為填補僱主團體保險限額不足而設計",
                "source_url": "https://www.manulife.com.hk/zh-hk/individual/products/health.html#page=4",
                "document_name": "宏利晉逸附加醫療單張",
                "page": 4,
                "quote": "填補公司醫保缺口，應付私家醫院突如其來的龐大開支。"
            }
        ],
        "premium_range": "每年 HK$1,350 – 5,200",
        "premium_available": True,
        "premium_notes": "按年齡與自選保障級別計算保費。",
        "key_terms": ["高達 85% 差額分攤", "靈活配搭基本住院計劃"],
        "exclusions": ["常規健康篩查", "投保前已有病症"],
        "source_urls": ["https://www.manulife.com.hk/zh-hk/individual/products/health.html"],
        "documents_found": ["宏利晉逸附加醫療單張"],
        "note": "宏利經典 SMM 附加超額保障。"
    },
    {
        "id": "topup-bowtie-combat",
        "category": "top-up-medical",
        "insurer": "Bowtie",
        "insurer_zh": "保泰人壽",
        "product_name": "Bowtie Combat Touchwood Medical",
        "product_name_zh": "Bowtie「觸木保」個人意外醫療加強保障",
        "plan_tiers": ["觸木保升級計劃（門診＋住院意外醫療全覆蓋）"],
        "coverage": [
            {
                "item": "意外醫療及門診實報實銷",
                "limit": "涵蓋跌打、物理治療、針灸、西醫急症，每年高達 HK$420,000",
                "source_url": "https://www.bowtie.com.hk/#page=2",
                "document_name": "Bowtie 觸木保產品條款",
                "page": 2,
                "quote": "意外門診及住院醫療費用實報實銷，物理治療及跌打無須醫生轉介。"
            },
            {
                "item": "公司醫保門診缺口填補",
                "limit": "彌補公司醫療門診次數不足、每次上限太低之痛點",
                "source_url": "https://www.bowtie.com.hk/#page=3",
                "document_name": "Bowtie 觸木保產品條款",
                "page": 3,
                "quote": "專為打工仔填補公司醫保物理治療及中醫跌打賠唔足之限制。"
            }
        ],
        "premium_range": "每月 HK$68 – 138（每年約 HK$816 – 1,656）",
        "premium_available": True,
        "premium_notes": "不分年齡性別劃一收費，免驗身免核保，純網上即時投保即時生效。",
        "key_terms": [
            "無需醫生轉介直接睇跌打及物理治療",
            "每月幾十蚊極低門檻加強保障",
            "保證續保至 80 歲"
        ],
        "exclusions": ["非意外引起的慢性肌肉勞損", "職業高危危險運動"],
        "source_urls": ["https://www.bowtie.com.hk/"],
        "documents_found": ["Bowtie 觸木保產品條款"],
        "note": "香港打工仔最喜愛之意外門診及跌打加強 Top-up 方案。"
    }
]

def main():
    print(f"Reading {DATA_FILE}...")
    with open(DATA_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)

    # 1. 確保現有 9 個類別中，medical 保持原樣
    existing_cats = {c["id"]: c for c in data.get("categories", [])}
    
    # 2. 新增 high-end-medical 與 top-up-medical
    new_cats = [
        {
            "id": "high-end-medical",
            "name_zh": "高端醫療保險",
            "count": len(HIGH_END_PRODUCTS),
            "insurers_with_premium": len([p for p in HIGH_END_PRODUCTS if p.get("premium_available")])
        },
        {
            "id": "top-up-medical",
            "name_zh": "Top-up 醫療保險",
            "count": len(TOP_UP_PRODUCTS),
            "insurers_with_premium": len([p for p in TOP_UP_PRODUCTS if p.get("premium_available")])
        }
    ]

    for nc in new_cats:
        existing_cats[nc["id"]] = nc

    # 保留自定義排序
    cat_order = [
        "home", "travel", "life", "critical-illness", "accident",
        "medical", "high-end-medical", "top-up-medical",
        "motor", "domestic-helper", "pet"
    ]
    data["categories"] = [existing_cats[cid] for cid in cat_order if cid in existing_cats]

    # 3. 處理 products：移除任何已存在的舊 high-end / top-up 測試條目，並追加全新獨立產品
    products = [p for p in data.get("products", []) if p.get("category") not in ("high-end-medical", "top-up-medical")]
    
    print(f"Existing non-high-end/top-up products count: {len(products)}")
    products.extend(HIGH_END_PRODUCTS)
    products.extend(TOP_UP_PRODUCTS)
    print(f"New total products count: {len(products)}")

    data["products"] = products

    # 4. 回寫檔案
    with open(DATA_FILE, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print("Successfully updated insurance-data.json with High-End and Top-Up products!")

if __name__ == "__main__":
    main()
