/** Build-time file integrity only. A hash does not establish policy meaning/currentness. */
import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
const root = new URL('../', import.meta.url);
const dir = new URL('public/docs/brochures/', root);
const entries = [];
for (const entry of (await readdir(dir, { withFileTypes: true })).sort((a,b) => a.name < b.name ? -1 : a.name > b.name ? 1 : 0)) {
  if (!entry.name.toLowerCase().endsWith('.pdf')) continue;
  if (!entry.isFile()) throw new Error(`PDF must be a regular file: ${entry.name}`);
  const bytes = await readFile(new URL(encodeURIComponent(entry.name), dir));
  if (bytes.subarray(0,5).toString() !== '%PDF-') throw new Error(`Not a PDF: ${entry.name}`);
  if (bytes.length > 32 * 1024 * 1024) throw new Error(`PDF exceeds the verified reader's 32 MiB limit: ${entry.name}`);
  entries.push([`/docs/brochures/${entry.name}`, createHash('sha256').update(bytes).digest('hex')]);
}
if (!entries.length) throw new Error('No mirrored PDFs found; refusing an empty manifest');
const output = new URL('src/lib/generated/pdf-manifest.ts', root);
const source = '// Generated by scripts/build_pdf_manifest.mjs. Byte identity, not content certification.\n' +
  'export const PDF_DOCUMENT_HASHES: Readonly<Record<string, string>> = ' + JSON.stringify(Object.fromEntries(entries), null, 2) + ';\n';
if (process.argv.includes('--check')) {
  if (await readFile(output, 'utf8') !== source) throw new Error('PDF manifest is stale. Review the changed PDFs, regenerate the manifest, and commit both together.');
} else {
  await mkdir(new URL('src/lib/generated/',root), {recursive:true});
  await writeFile(output, source);
}
console.log(`Verified manifest for ${entries.length} mirrored PDFs`);
